CREATE TABLE Personal_Details(
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
);

GRANT ALL ON Personal_Details to C##Devops;

Insert into Personal_Details
(person_id,first_name,last_name)
values (12345,'Ryan','Hipolito');


Select * from Personal_Details;
